import { SHOW_IMAGES } from "~/Constants/constants";

export const getCocktailImage = (id) => {
  if (!SHOW_IMAGES) return;
  switch (id.toString()) {
    case "1":
      return require("src/CocktailImages/1.jpg");
    case "2":
      return require("src/CocktailImages/2.jpg");
    case "3":
      return require("src/CocktailImages/3.jpg");
    case "4":
      return require("src/CocktailImages/4.jpg");
    case "5":
      return require("src/CocktailImages/5.jpg");
    case "6":
      return require("src/CocktailImages/6.jpg");
    case "7":
      return require("src/CocktailImages/7.jpg");
    case "8":
      return require("src/CocktailImages/8.jpg");
    case "9":
      return require("src/CocktailImages/9.jpg");
    case "10":
      return require("src/CocktailImages/10.jpg");
    case "11":
      return require("src/CocktailImages/11.jpg");
    case "12":
      return require("src/CocktailImages/12.jpg");
    case "13":
      return require("src/CocktailImages/13.jpg");
    case "14":
      return require("src/CocktailImages/14.jpg");
    case "15":
      return require("src/CocktailImages/15.jpg");
    case "16":
      return require("src/CocktailImages/16.jpg");
    case "17":
      return require("src/CocktailImages/17.jpg");
    case "18":
      return require("src/CocktailImages/18.jpg");
    case "19":
      return require("src/CocktailImages/19.jpg");
    case "20":
      return require("src/CocktailImages/20.jpg");
    case "21":
      return require("src/CocktailImages/21.jpg");
    case "22":
      return require("src/CocktailImages/22.jpg");
    case "23":
      return require("src/CocktailImages/23.jpg");
    case "24":
      return require("src/CocktailImages/24.jpg");
    case "25":
      return require("src/CocktailImages/25.jpg");
    case "26":
      return require("src/CocktailImages/26.jpg");
    case "27":
      return require("src/CocktailImages/27.jpg");
    case "28":
      return require("src/CocktailImages/28.jpg");
    case "29":
      return require("src/CocktailImages/29.jpg");
    case "30":
      return require("src/CocktailImages/30.jpg");
    case "31":
      return require("src/CocktailImages/31.jpg");
    case "32":
      return require("src/CocktailImages/32.jpg");
    case "33":
      return require("src/CocktailImages/33.jpg");
    case "34":
      return require("src/CocktailImages/34.jpg");
    case "35":
      return require("src/CocktailImages/35.jpg");
    case "36":
      return require("src/CocktailImages/36.jpg");
    case "37":
      return require("src/CocktailImages/37.jpg");
    case "38":
      return require("src/CocktailImages/38.jpg");
    case "39":
      return require("src/CocktailImages/39.jpg");
    case "40":
      return require("src/CocktailImages/40.jpg");
    case "41":
      return require("src/CocktailImages/41.jpg");
    case "42":
      return require("src/CocktailImages/42.jpg");
    case "43":
      return require("src/CocktailImages/43.jpg");
    case "44":
      return require("src/CocktailImages/44.jpg");
    case "45":
      return require("src/CocktailImages/45.jpg");
    case "46":
      return require("src/CocktailImages/46.jpg");
    case "47":
      return require("src/CocktailImages/47.jpg");
    case "48":
      return require("src/CocktailImages/48.jpg");
    case "49":
      return require("src/CocktailImages/49.jpg");
    case "50":
      return require("src/CocktailImages/50.jpg");
    case "51":
      return require("src/CocktailImages/51.jpg");
    case "52":
      return require("src/CocktailImages/52.jpg");
    case "53":
      return require("src/CocktailImages/53.jpg");
    case "54":
      return require("src/CocktailImages/54.jpg");
    case "55":
      return require("src/CocktailImages/55.jpg");
    case "56":
      return require("src/CocktailImages/56.jpg");
    case "57":
      return require("src/CocktailImages/57.jpg");
    case "58":
      return require("src/CocktailImages/58.jpg");
    case "59":
      return require("src/CocktailImages/59.jpg");
    case "60":
      return require("src/CocktailImages/60.jpg");
    case "61":
      return require("src/CocktailImages/61.jpg");
    case "62":
      return require("src/CocktailImages/62.jpg");
    case "63":
      return require("src/CocktailImages/63.jpg");
    case "64":
      return require("src/CocktailImages/64.jpg");
    case "65":
      return require("src/CocktailImages/65.jpg");
    case "66":
      return require("src/CocktailImages/66.jpg");
    case "67":
      return require("src/CocktailImages/67.jpg");
    case "68":
      return require("src/CocktailImages/68.jpg");
    case "69":
      return require("src/CocktailImages/69.jpg");
    case "70":
      return require("src/CocktailImages/70.jpg");
    case "71":
      return require("src/CocktailImages/71.jpg");
    case "72":
      return require("src/CocktailImages/72.jpg");
    case "73":
      return require("src/CocktailImages/73.jpg");
    case "74":
      return require("src/CocktailImages/74.jpg");
    case "75":
      return require("src/CocktailImages/75.jpg");
    case "76":
      return require("src/CocktailImages/76.jpg");
    case "77":
      return require("src/CocktailImages/77.jpg");
    case "78":
      return require("src/CocktailImages/78.jpg");
    case "79":
      return require("src/CocktailImages/79.jpg");
    case "80":
      return require("src/CocktailImages/80.jpg");
    case "81":
      return require("src/CocktailImages/81.jpg");
    case "82":
      return require("src/CocktailImages/82.jpg");
    case "83":
      return require("src/CocktailImages/83.jpg");
    case "84":
      return require("src/CocktailImages/84.jpg");
    case "85":
      return require("src/CocktailImages/85.jpg");
    case "86":
      return require("src/CocktailImages/86.jpg");
    case "87":
      return require("src/CocktailImages/87.jpg");
    case "88":
      return require("src/CocktailImages/88.jpg");
    case "89":
      return require("src/CocktailImages/89.jpg");
    case "90":
      return require("src/CocktailImages/90.jpg");
    case "91":
      return require("src/CocktailImages/91.jpg");
    case "92":
      return require("src/CocktailImages/92.jpg");
    case "93":
      return require("src/CocktailImages/93.jpg");
    case "94":
      return require("src/CocktailImages/94.jpg");
    case "95":
      return require("src/CocktailImages/95.jpg");
    case "96":
      return require("src/CocktailImages/96.jpg");
    case "97":
      return require("src/CocktailImages/97.jpg");
    case "98":
      return require("src/CocktailImages/98.jpg");
    case "99":
      return require("src/CocktailImages/99.jpg");
    case "100":
      return require("src/CocktailImages/100.jpg");
    case "101":
      return require("src/CocktailImages/101.jpg");
    case "102":
      return require("src/CocktailImages/102.jpg");
    case "103":
      return require("src/CocktailImages/103.jpg");
    case "104":
      return require("src/CocktailImages/104.jpg");
    case "105":
      return require("src/CocktailImages/105.jpg");
    case "106":
      return require("src/CocktailImages/106.jpg");
    case "107":
      return require("src/CocktailImages/107.jpg");
    case "108":
      return require("src/CocktailImages/108.jpg");
    case "109":
      return require("src/CocktailImages/109.jpg");
    case "110":
      return require("src/CocktailImages/110.jpg");
    case "111":
      return require("src/CocktailImages/111.jpg");
    case "112":
      return require("src/CocktailImages/112.jpg");
    case "113":
      return require("src/CocktailImages/113.jpg");
    case "114":
      return require("src/CocktailImages/114.jpg");
    case "115":
      return require("src/CocktailImages/115.jpg");
    case "116":
      return require("src/CocktailImages/116.jpg");
    case "117":
      return require("src/CocktailImages/117.jpg");
    case "118":
      return require("src/CocktailImages/118.jpg");
    case "119":
      return require("src/CocktailImages/119.jpg");
    case "120":
      return require("src/CocktailImages/120.jpg");
    case "121":
      return require("src/CocktailImages/121.jpg");
    case "122":
      return require("src/CocktailImages/122.jpg");
    case "123":
      return require("src/CocktailImages/123.jpg");
    case "124":
      return require("src/CocktailImages/124.jpg");
    case "125":
      return require("src/CocktailImages/125.jpg");
    case "126":
      return require("src/CocktailImages/126.jpg");
    case "127":
      return require("src/CocktailImages/127.jpg");
    case "128":
      return require("src/CocktailImages/128.jpg");
    case "129":
      return require("src/CocktailImages/129.jpg");
    case "130":
      return require("src/CocktailImages/130.jpg");
    case "131":
      return require("src/CocktailImages/131.jpg");
    case "132":
      return require("src/CocktailImages/132.jpg");
    case "133":
      return require("src/CocktailImages/133.jpg");
    case "134":
      return require("src/CocktailImages/134.jpg");
    case "135":
      return require("src/CocktailImages/135.jpg");
    case "136":
      return require("src/CocktailImages/136.jpg");
    case "137":
      return require("src/CocktailImages/137.jpg");
    case "138":
      return require("src/CocktailImages/138.jpg");
    case "139":
      return require("src/CocktailImages/139.jpg");
    case "140":
      return require("src/CocktailImages/140.jpg");
    case "141":
      return require("src/CocktailImages/141.jpg");
    case "142":
      return require("src/CocktailImages/142.jpg");
    case "143":
      return require("src/CocktailImages/143.jpg");
    case "144":
      return require("src/CocktailImages/144.jpg");
    case "145":
      return require("src/CocktailImages/145.jpg");
    case "146":
      return require("src/CocktailImages/146.jpg");
    case "147":
      return require("src/CocktailImages/147.jpg");
    case "148":
      return require("src/CocktailImages/148.jpg");
    case "149":
      return require("src/CocktailImages/149.jpg");
    case "150":
      return require("src/CocktailImages/150.jpg");
    case "151":
      return require("src/CocktailImages/151.jpg");
    case "152":
      return require("src/CocktailImages/152.jpg");
    case "153":
      return require("src/CocktailImages/153.jpg");
    case "154":
      return require("src/CocktailImages/154.jpg");
    case "155":
      return require("src/CocktailImages/155.jpg");
    case "156":
      return require("src/CocktailImages/156.jpg");
    case "157":
      return require("src/CocktailImages/157.jpg");
    case "158":
      return require("src/CocktailImages/158.jpg");
    case "159":
      return require("src/CocktailImages/159.jpg");
    case "160":
      return require("src/CocktailImages/160.jpg");
    case "161":
      return require("src/CocktailImages/161.jpg");
    case "162":
      return require("src/CocktailImages/162.jpg");
    case "163":
      return require("src/CocktailImages/163.jpg");
    case "164":
      return require("src/CocktailImages/164.jpg");
    case "165":
      return require("src/CocktailImages/165.jpg");
    case "166":
      return require("src/CocktailImages/166.jpg");
    case "167":
      return require("src/CocktailImages/167.jpg");
    case "168":
      return require("src/CocktailImages/168.jpg");
    case "169":
      return require("src/CocktailImages/169.jpg");
    case "170":
      return require("src/CocktailImages/170.jpg");
    case "171":
      return require("src/CocktailImages/171.jpg");
    case "172":
      return require("src/CocktailImages/172.jpg");
    case "173":
      return require("src/CocktailImages/173.jpg");
    case "174":
      return require("src/CocktailImages/174.jpg");
    case "175":
      return require("src/CocktailImages/175.jpg");
    case "176":
      return require("src/CocktailImages/176.jpg");
    case "177":
      return require("src/CocktailImages/177.jpg");
    case "178":
      return require("src/CocktailImages/178.jpg");
    case "179":
      return require("src/CocktailImages/179.jpg");
    case "180":
      return require("src/CocktailImages/180.jpg");
    case "181":
      return require("src/CocktailImages/181.jpg");
    case "182":
      return require("src/CocktailImages/182.jpg");
    case "183":
      return require("src/CocktailImages/183.jpg");
    case "184":
      return require("src/CocktailImages/184.jpg");
    case "185":
      return require("src/CocktailImages/185.jpg");
    case "186":
      return require("src/CocktailImages/186.jpg");
    case "187":
      return require("src/CocktailImages/187.jpg");
    case "188":
      return require("src/CocktailImages/188.jpg");
    case "189":
      return require("src/CocktailImages/189.jpg");
    case "190":
      return require("src/CocktailImages/190.jpg");
    case "191":
      return require("src/CocktailImages/191.jpg");
    case "192":
      return require("src/CocktailImages/192.jpg");
    case "193":
      return require("src/CocktailImages/193.jpg");
    case "194":
      return require("src/CocktailImages/194.jpg");
    case "195":
      return require("src/CocktailImages/195.jpg");
    case "196":
      return require("src/CocktailImages/196.jpg");
    case "197":
      return require("src/CocktailImages/197.jpg");
    case "198":
      return require("src/CocktailImages/198.jpg");
    case "199":
      return require("src/CocktailImages/199.jpg");
    case "200":
      return require("src/CocktailImages/200.jpg");
    case "201":
      return require("src/CocktailImages/201.jpg");
    case "202":
      return require("src/CocktailImages/202.jpg");
    case "203":
      return require("src/CocktailImages/203.jpg");
    case "204":
      return require("src/CocktailImages/204.jpg");
    case "205":
      return require("src/CocktailImages/205.jpg");
    case "206":
      return require("src/CocktailImages/206.jpg");
    case "207":
      return require("src/CocktailImages/207.jpg");
    case "208":
      return require("src/CocktailImages/208.jpg");
    case "209":
      return require("src/CocktailImages/209.jpg");
    default:
      return undefined;
  }
};
